import contextlib
import io
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

from scripts import hf_space_deploy as deploy


def commit_fixture(root: Path) -> str:
    """Local-only Git object fixture; never uses remote credentials or signing."""
    commands = (
        ("init", "-q"), ("config", "core.autocrlf", "false"), ("add", "."),
        ("-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid",
         "commit", "--no-gpg-sign", "-qm", "offline fixture"),
    )
    for command in commands:
        subprocess.run(["git", "-C", str(root), *command], check=True, capture_output=True)
    return subprocess.check_output(["git", "-C", str(root), "rev-parse", "HEAD"], text=True).strip()


class ClosedOutputTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.space = self.root / "space"
        self.space.mkdir()
        (self.root / ".gitignore").write_text("__pycache__/\n*.pyc\n.env\n", encoding="utf-8")
        (self.space / "server.py").write_bytes(b"value = 1\n")
        (self.space / "README.md").write_bytes(
            b"---\nsdk: docker\napp_port: 7860\npinned: true\nlicense: apache-2.0\n---\n"
        )
        self.revision = commit_fixture(self.root)
        self.binding = deploy._source_binding("szl-holdings/szl-router", self.revision)

    def snapshot(self):
        return deploy._source_snapshot(self.space, self.revision)

    def assert_source_rejected(self, code):
        with self.assertRaises(deploy.PublicationSourceError) as caught:
            self.snapshot()
        self.assertEqual(code, caught.exception.code)

    def test_ignored_bytecode_and_environment_never_enter_release(self):
        expected_source = self.snapshot()
        cache = self.space / "__pycache__"
        cache.mkdir()
        for index in range(8):
            (cache / f"module{index}.cpython-312.pyc").write_bytes(b"generated bytecode")
        (self.space / ".env").write_bytes(b"TEST_ONLY=not-a-credential\n")
        self.assertEqual(expected_source, self.snapshot())
        release = self.root / "release"
        expected = deploy._stage_release(release, self.snapshot(), self.binding)
        self.assertEqual({"README.md", "server.py", "SOURCE_BINDING.json"}, set(expected))
        self.assertEqual(self.binding, json.loads(expected["SOURCE_BINDING.json"]))
        self.assertFalse(any(path.suffix == ".pyc" for path in release.rglob("*")))
        self.assertFalse((release / ".env").exists())

    def test_release_bytes_are_deterministic_and_bound_to_snapshot(self):
        snapshot = self.snapshot()
        (self.space / "server.py").write_bytes(b"changed after snapshot\n")
        first = deploy._stage_release(self.root / "one", snapshot, self.binding)
        second = deploy._stage_release(self.root / "two", snapshot, self.binding)
        self.assertEqual(first, second)
        self.assertEqual(b"value = 1\n", (self.root / "one/server.py").read_bytes())

    def test_main_publishes_only_closed_set_with_parent_cas_and_readback(self):
        from unittest.mock import Mock

        api = Mock()
        api.repo_info.side_effect = [
            SimpleNamespace(sha="b" * 40),
            SimpleNamespace(sha="c" * 40, private=False),
            SimpleNamespace(sha="c" * 40, private=False),
        ]
        def upload(**kwargs):
            release = Path(kwargs["folder_path"])
            self.assertEqual("b" * 40, kwargs["parent_commit"])
            self.assertEqual("*", kwargs["delete_patterns"])
            expected = dict(self.snapshot())
            expected["SOURCE_BINDING.json"] = (json.dumps(self.binding, indent=2, sort_keys=True) + "\n").encode()
            deploy._validate_release_tree(release, expected)
            return SimpleNamespace(oid="c" * 40)
        api.upload_folder.side_effect = upload
        factory = Mock(return_value=api)
        argv = ["publisher", "--space-dir", str(self.space), "--token", "test-only",
                "--source-repository", "szl-holdings/szl-router", "--source-revision", self.revision]
        with patch.dict(sys.modules, {"huggingface_hub": SimpleNamespace(HfApi=factory)}), \
                patch.object(sys, "argv", argv), contextlib.redirect_stdout(io.StringIO()) as output:
            deploy.main()
        api.upload_folder.assert_called_once()
        api.restart_space.assert_called_once_with(repo_id="SZLHOLDINGS/llm-router-live")
        api.update_repo_settings.assert_called_once_with(
            repo_id="SZLHOLDINGS/llm-router-live", repo_type="space", private=False
        )
        receipt = json.loads(output.getvalue())
        self.assertEqual("c" * 40, receipt["observed_revision"])
        self.assertEqual(self.revision, receipt["source_revision"])
        self.assertFalse(receipt["space_created"])

    def test_main_rejects_dirty_source_before_provider_construction(self):
        from unittest.mock import Mock

        factory = Mock()
        (self.space / "server.py").write_bytes(b"dirty\n")
        argv = ["publisher", "--space-dir", str(self.space), "--token", "test-only",
                "--source-revision", self.revision]
        with patch.dict(sys.modules, {"huggingface_hub": SimpleNamespace(HfApi=factory)}), \
                patch.object(sys, "argv", argv), self.assertRaises(deploy.PublicationSourceError):
            deploy.main()
        factory.assert_not_called()

    def test_changed_deleted_and_untracked_source_fail_closed(self):
        tracked = self.space / "server.py"
        for mutation in ("change", "delete", "untracked", "binding"):
            with self.subTest(mutation=mutation):
                tracked.write_bytes(b"value = 1\n")
                extra = None
                if mutation == "change":
                    tracked.write_bytes(b"different\n")
                elif mutation == "delete":
                    tracked.unlink()
                else:
                    extra = self.space / ("unexpected.txt" if mutation == "untracked" else "SOURCE_BINDING.json")
                    extra.write_bytes(b"unexpected\n")
                self.assert_source_rejected("SOURCE_WORKTREE_DIRTY")
                if extra:
                    extra.unlink()
        tracked.write_bytes(b"value = 1\n")

    def test_staged_source_change_is_rejected(self):
        (self.space / "server.py").write_bytes(b"staged\n")
        subprocess.run(["git", "-C", str(self.root), "add", "space/server.py"], check=True)
        self.assert_source_rejected("SOURCE_WORKTREE_DIRTY")

    def test_wrong_revision_is_rejected(self):
        self.revision = "f" * 40
        self.assert_source_rejected("SOURCE_CHECKOUT_MISMATCH")

    def test_unsafe_tree_records_are_rejected(self):
        real_git = deploy._git_bytes
        for record in (
            b"120000 blob " + b"a" * 40 + b"\tspace/link\0",
            b"160000 commit " + b"a" * 40 + b"\tspace/submodule\0",
            b"100644 blob " + b"a" * 40 + b"\tspace/../escape\0",
            b"100644 blob " + b"a" * 40 + b"\tspace/__pycache__/cache.pyc\0",
            b"100644 blob " + b"a" * 40 + b"\tspace/SOURCE_BINDING.json\0",
            b"100644 blob " + b"a" * 40 + b"\telsewhere/file\0",
            b"malformed\0",
        ):
            with self.subTest(record=record):
                def read(root, *args):
                    return record if args[0] == "ls-tree" else real_git(root, *args)
                with patch.object(deploy, "_git_bytes", side_effect=read):
                    self.assert_source_rejected("SOURCE_TREE_UNSAFE")

    def test_unsafe_stage_paths_and_binding_override_are_rejected_before_creation(self):
        for relative in ("../escape", "/absolute", "a\\b", "C:/drive", "a//b", "a/./b",
                         "__pycache__/cache.pyc", "SOURCE_BINDING.json", "a\ncontrol"):
            with self.subTest(relative=relative):
                with self.assertRaises(deploy.PublicationSourceError):
                    deploy._stage_release(self.root / "release", {relative: b"x"}, self.binding)
                self.assertFalse((self.root / "release").exists())

    def test_missing_extra_modified_and_empty_directory_outputs_are_rejected(self):
        for mutation, code in (("missing", "PUBLICATION_OUTPUT_SET_MISMATCH"),
                               ("extra", "PUBLICATION_OUTPUT_SET_MISMATCH"),
                               ("directory", "PUBLICATION_OUTPUT_SET_MISMATCH"),
                               ("modified", "PUBLICATION_BYTE_DRIFT")):
            with self.subTest(mutation=mutation):
                release = self.root / mutation
                expected = deploy._stage_release(release, self.snapshot(), self.binding)
                if mutation == "missing":
                    (release / "server.py").unlink()
                elif mutation == "extra":
                    (release / "extra.txt").write_bytes(b"extra")
                elif mutation == "directory":
                    (release / "empty-extra").mkdir()
                else:
                    (release / "server.py").write_bytes(b"modified")
                with self.assertRaises(deploy.PublicationSourceError) as caught:
                    deploy._validate_release_tree(release, expected)
                self.assertEqual(code, caught.exception.code)

    def test_release_symlink_and_broken_symlink_are_rejected_when_supported(self):
        release = self.root / "release"
        expected = deploy._stage_release(release, self.snapshot(), self.binding)
        link = release / "link"
        for target in (self.space, self.root / "missing"):
            try:
                link.symlink_to(target, target_is_directory=True)
            except OSError as exc:
                self.skipTest(f"Symlink creation unavailable: {type(exc).__name__}")
            with self.assertRaises(deploy.PublicationSourceError) as caught:
                deploy._validate_release_tree(release, expected)
            self.assertEqual("PUBLICATION_OUTPUT_UNSAFE", caught.exception.code)
            link.unlink()


class DeployAdmissionTests(unittest.TestCase):
    def _space(self, front_matter: str) -> tuple[tempfile.TemporaryDirectory, Path]:
        temporary = tempfile.TemporaryDirectory()
        space = Path(temporary.name) / "space"
        space.mkdir()
        (space / "README.md").write_text(front_matter, encoding="utf-8")
        return temporary, space

    def test_exact_top_level_front_matter_is_accepted(self):
        temporary, space = self._space(
            "---\nsdk: docker # required runtime\napp_port: '7860'\npinned: true\nlicense: apache-2.0\n---\n"
        )
        self.addCleanup(temporary.cleanup)
        deploy._validate_readme(space)

    def test_comment_cannot_spoof_sdk_or_port(self):
        temporary, space = self._space(
            "---\nsdk: static\n# sdk: docker\napp_port: 80 # app_port: 7860\n---\n"
        )
        self.addCleanup(temporary.cleanup)
        with self.assertRaises(SystemExit):
            deploy._validate_readme(space)

    def test_duplicate_runtime_keys_are_rejected(self):
        temporary, space = self._space(
            "---\nsdk: docker\nsdk: static\napp_port: 7860\n---\n"
        )
        self.addCleanup(temporary.cleanup)
        with self.assertRaises(SystemExit):
            deploy._validate_readme(space)

    def test_directory_symlink_is_rejected_when_supported(self):
        temporary, space = self._space("---\nsdk: docker\napp_port: 7860\n---\n")
        self.addCleanup(temporary.cleanup)
        outside = Path(temporary.name) / "outside"
        outside.mkdir()
        (outside / "secret.txt").write_text("not deployable", encoding="utf-8")
        link = space / "linked-directory"
        try:
            link.symlink_to(outside, target_is_directory=True)
        except OSError as exc:
            self.skipTest(f"Directory symlinks are unavailable: {type(exc).__name__}")
        with self.assertRaises(SystemExit):
            deploy._validate_source_tree(space)


if __name__ == "__main__":
    unittest.main()
